### ISSUE TITLE
统一社会代码校验算法不准确。。。

### ISSUE THREAD

**Issue by x1aoj1ang** [wellenzhong/cn-validator#2]
https://github.com/wellenzhong/cn-validator/blob/eb0902428719ce21baa97c01d362f380b3348ead/src/validator.js#L128

这行要改成
```js
let validateCode = baseCarsArr[idx%baseCarsArr.length] //汇总结果对31求余,再用31减去余数,取对应位的值作为校验码
```

否则在校验位为0的情况下会出错。

感谢提供此校验算法。

**Comment by wellenzhong** [comment]
感谢指正！已修复！
